04.2 task
Verce11o/resume-view pull request #5
Opened 2024-05-07 15:09 UTC by Verce11o

2024-05-08 07:18 UTC, kiryalovik commented on echo-service/cmd/main.go
> +		slog.Error("Error creating new view client", "error", err.Error())
это может быть Errorf

2024-05-08 07:20 UTC, kiryalovik commented on employee-service/cmd/main.go
> +	quit := make(chan os.Signal, 1)
Это должно быть application.Wait()

2024-05-08 07:21 UTC, kiryalovik commented on employee-service/internal/app/app.go
> +	db, err := postgresLib.New(ctx, postgresLib.Config{
Должна инициализироваться только одна из баз в зависимости от того какая у тебя главная.

2024-05-08 07:29 UTC, kiryalovik commented on Makefile
> +migrate-up:
В прошлый раз прозевал
make build должен делать build image а не просто билд приложения

2024-05-08 07:47 UTC, kiryalovik commented on employee-service/internal/handler/handler.go
> +
Включи линтер whitespace 
А также bodyclose, errname, gci, gocritic, gofmt, goimport, gosec, importas, interfacebloat, lll, nestif, nilerr, nilnil, nlreturn, nosprintfhostport, protogetter, rowserrcheck, sqlclosecheck, stylecheck, revive, wrapcheck,

2024-05-08 07:49 UTC, kiryalovik commented on employee-service/internal/repository/mongodb/employee.go
> +var employeeLimit = 5
Почему variable, а не const?

2024-05-08 08:10 UTC, kiryalovik requested changes
Первый раунд =) 
Пока исправь то что уже указал, после добавлю.

2024-05-08 08:10 UTC, kiryalovik commented on employee-service/internal/repository/postgres/employee.go
> +		return pgx.ErrNoRows
Не подменил ошибку на общую

2024-05-08 08:10 UTC, kiryalovik commented on employee-service/internal/repository/postgres/employee.go
> +		return models.Employee{}, err
Как ты узнаешь обновилось ли что-то?

2024-05-08 08:10 UTC, kiryalovik commented on employee-service/internal/repository/postgres/employee_test.go
> +			wantErr: true,
Нет проверки что за ошибка пришла

2024-05-08 08:10 UTC, kiryalovik commented on employee-service/internal/repository/postgres/employee_test.go
> +			_, err := repo.GetEmployee(ctx, tt.employeeID)
Нет проверки полученного результата

2024-05-08 08:10 UTC, kiryalovik commented on employee-service/internal/repository/postgres/employee_test.go
> +	_, err = dbPool.Exec(ctx, "INSERT INTO positions (id, name, salary)  VALUES  ($1, $2, $3)", positionID, "Go Developer", 123456)
При изменении структуры таблицы тебе придется править все тесты

2024-05-08 08:10 UTC, kiryalovik commented on employee-service/internal/repository/postgres/employee_test.go
> +	repo := NewEmployeeRepository(dbPool)
Дубликация кода инициализаии в каждой функции

2024-05-08 08:10 UTC, kiryalovik commented on employee-service/internal/repository/postgres/employee_test.go
> +			_, err := repo.UpdateEmployee(ctx, tt.employeeID, tt.request)
нет проверки что что-то изменилось

2024-05-08 08:10 UTC, kiryalovik commented on employee-service/internal/repository/postgres/employee_test.go
> +			if tt.wantErr {
Нет проверки что пришла нужная ошибка

2024-05-08 10:21 UTC, Verce11o commented on employee-service/internal/repository/mongodb/employee.go
> +func (p *EmployeeRepository) CreateEmployee(ctx context.Context, employeeID uuid.UUID, positionID uuid.UUID, request api.CreateEmployee) (models.Employee, error) {
Это модельки, сгенерированные через oapi-codegen. Мне на уровне сервисов их конвертировать в локальные модельки?

2024-05-08 10:24 UTC, Verce11o commented on echo-service/cmd/main.go
> +		slog.Error("Error creating new view client", "error", err.Error())
у слога нет метода Errorf

2024-05-08 10:26 UTC, Verce11o commented on employee-service/internal/repository/postgres/employee.go
> +	tx, err := p.db.Begin(ctx)
По заданию должен был быть метод, который создаст и employee, и position, и должен быть потокобезопасным. Подумал транзакция хорошо подойдет

2024-05-08 10:34 UTC, kiryalovik commented on employee-service/internal/repository/mongodb/employee.go
> +func (p *EmployeeRepository) CreateEmployee(ctx context.Context, employeeID uuid.UUID, positionID uuid.UUID, request api.CreateEmployee) (models.Employee, error) {
На самом деле это надо сделать еще в хэндлере. Сервис это уже бизнес уровень, который о транспорте который к нему постучал уже не должен знать и может быть вызван из любого транспортного уровня, будь то rpc http или вообще какой-нибудь graphql

2024-05-08 10:36 UTC, kiryalovik commented on employee-service/internal/repository/postgres/employee.go
> +	tx, err := p.db.Begin(ctx)
Не заметил второй инсерт

2024-05-12 20:12 UTC, Verce11o commented
Выполнил все правки, но часть с транзакциями вынесу в отдельный PR

2024-05-13 10:36 UTC, kiryalovik approved these changes

2024-05-13 10:41 UTC, merged